[workspace]
resolver = "2"

members = [ "casper-contract-tests", "cspr-session",
  "limit-order-proto",
]
exclude = [
    "casper-contract-proto"
]

[workspace.package]
name = "market-making"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
