[package]
name = "casper-contract-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
casper-contract = {version="4.0.0", features=["std", "test-support"]}
casper-types = {version="4.0.1"}
bincode = "1.3.3"
serde = "1"

[build]
target = "wasm32-unknown-unknown"